# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:16-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=#L654321o
      - POSTGRES_USER=wh_user
      - POSTGRES_DB=wh